language: java
dist: trusty

jdk:
  - oraclejdk11
  
matrix:
  include:
    - jdk: openjdk12

script:
  - mvn -B clean test jacoco:report

addons:
   hosts:
       - travis
   hostname: travis

before_script:
  - pip install --user codecov

after_success:
  - codecov
