language: java
dist: trusty

jdk:
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

script:
  - mvn -B clean test jacoco:report

addons:
   hosts:
       - travis
   hostname: travis

before_script:
  - pip install --user codecov

after_success:
  - codecov
  - mvn sonar:sonar -Dsonar.projectKey=javadev_underscore-java11 -Dsonar.organization=javadev-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN
